name: Release

on:
  push:
  
jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      
      - run: npm install --save-exact
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'update the version'
          branch: main
